#!/bin/sh

TASKS_FILE=~/Documents/Org/Tareas.md
MAX_TASKS=10
EDITOR=vim
DATE_FORMAT=+%y-%m-%d

NOW=`date +%s`

natural2date() {
  DATESTRING=`echo $1 | grep -oP "\(.*\)" | sed 's/(\(.*\))/\1/'`

  if [ ! -z "$DATESTRING" ]; then
    DATE=`date -d "$DATESTRING" $DATE_FORMAT`
    REST=`echo $1 | sed 's/(.*)//'`

    DATE="\e[0;32m$DATE\e[0m"

    echo $DATE $REST 
  fi
}

if [ $# = 0 ]; then 
  echo ---

  grep "\* \[ \] " "$TASKS_FILE" \
    | sed 's,^.*\* \[ \],,g' \
    | while read -r line ; do
        natural2date "$line"
      done | sort

  echo ---

elif [ $1 = a ]; then
  read -p '>> ' TASK
  read -p '>> ' DATESTRING

  DATE=`date -d "$DATESTRING" $DATE_FORMAT`

  echo "* [ ] $TASK ($DATE)" >> $TASKS_FILE
  echo "Added $TASK ($DATE)"

elif [ $1 = c ]; then 
  sed -i '/^.*\* \[X\]/d' $TASKS_FILE

elif [ $1 = e ]; then 
  $EDITOR $TASKS_FILE

fi
